language: cpp

sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

os:
  - linux

compiler:
  - gcc

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.3.0-Linux-x86_64.tar.gz
      && tar -xzf cmake-3.3.0-Linux-x86_64.tar.gz
      && sudo cp -fR cmake-3.3.0-Linux-x86_64/* /usr
      ; fi

before_script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_APP=off -DBUILD_TESTS=on -DCODE_METRICS=off -DCODE_CHECK=off -DBUILD_TESTS_COVERAGE=off -DVALGRIND_CHECK=off -DINSTALLABLE=on

script:
  - make
  - ./tester

notifications:
  email: false

